name: cicd
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "hello"
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing"
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploying the app'
